runtime: nodejs8
env_variables:
  JWT_SECRET_KEY: "mankind"
  MAILGUN_API_KEY: "key-696537b9c51104e877a86451ccbb9d45"
  MAILGUN_SENDERS_NAME: "excuts"
  MAILGUN_DOMAIN_NAME: "excuts.com"
  MONGOHQ_URL: "mongodb://mayowamakinde:oreoluwa53@ds163630.mlab.com:63630/takemeout"
  MAILGUN_SENDERS_EMAIL: "excuts2018@gmail.com"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
